---

- name: Dowload NVIDIA .deb
  get_url:
    url: http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64/cuda-repo-ubuntu1604_8.0.61-1_amd64.deb
    dest: /tmp/nvidia.deb

- name: Install Drivers
  apt:
    deb: /tmp/nvidia.deb

- name: Install NVIDIA packages
  apt:
    update_cache: yes
    name: "{{ item }}"
    state: latest
  with_items: "{{ nvidia_packages }}"

# -- - name: Download Driver Package
# --   get_url: 
# --     url: http://us.download.nvidia.com/XFree86/Linux-x86_64/{{ nvidia_driver_version }}/NVIDIA-Linux-x86_64-{{ nvidia_driver_version }}.run
# --     dest: /tmp/nvidia-driver-{{ nvidia_driver_version }}.run
# --     mode: u+rx
# --   when: not nvidia_driver_install_toolkit
# -- #   checksum: md5:95a6401db6576eaeea6ba4bc06fb61d2
# -- 
# -- - name: Run Install Script
# --   command: /tmp/nvidia-driver-{{ nvidia_driver_version }}.run --accept-license --silent --no-opengl-files --no-nouveau-check --no-x-check {% if nvidia_driver_force_reinstall %}--force-update{% endif %} creates=/usr/bin/nvidia-smi
# --   when: not nvidia_
# --   when: not nvidia_driver_install_toolkit
